import { Router } from 'express'
import { z } from 'zod'
import { pool } from '../db.js'
import { config } from '../config.js'
import { requireAdmin } from '../middleware/auth.js'
import { UPLOAD_PATH_RE, diskPathOf, inspectImage } from '../middleware/upload.js'
const abs=p=>(p?`${config.publicUrl}${p}`:null); const slug='home-about-us'; const pageSlug='about-page'; const text=max=>z.string().trim().max(max).default('')
const DEFAULT_PAGE={hero:{badge:'وکالت با تخصص، صداقت و امانت‌داری',title:'گروه حقوقی غدیری',description:'این یک متن نمونه است. معرفی کوتاهی از دفتر، سابقه، و ارزش‌های شما.',primaryLabel:'با ما تماس بگیرید',primaryLink:'/contact-us',secondaryLabel:'آشنایی با تیم',secondaryLink:'#team',keywords:['حق','امانت','تخصص']},policiesTitle:'خط مشی گروه حقوقی غدیری',policiesSubtitle:'روی هر مورد کلیک کنید تا جزئیاتش را ببینید.',policies:[{title:'حق‌مداری',short:'حفاظت از حقوق موکل در چارچوب قانون و انصاف.',heading:'دفاع از حق، تنها در چارچوب قانون',text:'هر پرونده با این پرسش آغاز می‌شود که حق موکل چیست.',practice:'نقاط قوت و ضعف پرونده با موکل مرور می‌شود.',points:['بررسی دقیق مستندات','دفاع بدون تعارض منافع']}],ethicsTitle:'تعهدات اخلاقی ما',ethicsSubtitle:'چارچوبی که هر عضو تیم به آن پایبند است.',ethics:['رازداری مطلق درباره اطلاعات موکل','پرهیز از تعارض منافع','صداقت در ارائه مشاوره'],ethicsQuote:'وکالت، امانتی است که با رازداری و صداقت حفظ می‌شود.',teamTitle:'آشنایی با همکاران ما',teamSubtitle:'متخصصانی که پرونده شما را به عهده می‌گیرند.',team:[],principlesTitle:'اصولی که وکالت را معنا می‌دهد',principlesSubtitle:'اصول گروه حقوقی غدیری',principles:[],reasonsTitle:'چرا گروه حقوقی غدیری؟',reasonsSubtitle:'دلایلی که موکلان ما را انتخاب می‌کنند.',reasons:[],casesTitle:'گزیده‌ای از پرونده‌های موفق',casesSubtitle:'نوع دعوا و روش حل نمایش داده می‌شود.',cases:[],reviewsTitle:'آنچه موکلان ما می‌گویند',reviewsSubtitle:'تجربه موکلان ما.',reviews:[],stats:[]}
const item=z.object({title:text(255),text:text(5000),short:text(1000),heading:text(500),practice:text(2000),points:z.array(text(500)).max(20).default([]),icon:text(100)})
const pageSchema=z.object({hero:z.object({badge:text(255),title:text(500),description:text(3000),primaryLabel:text(100),primaryLink:text(255),secondaryLabel:text(100),secondaryLink:text(255),keywords:z.array(text(100)).max(20).default([])}).default({}),policiesTitle:text(255),policiesSubtitle:text(1000),policies:z.array(item).max(30).default([]),ethicsTitle:text(255),ethicsSubtitle:text(1000),ethics:z.array(text(1000)).max(30).default([]),ethicsQuote:text(1000),teamTitle:text(255),teamSubtitle:text(1000),team:z.array(z.object({name:text(255),field:text(255),edu:text(500),photo:z.string().regex(UPLOAD_PATH_RE).nullable().optional()})).max(50).default([]),principlesTitle:text(255),principlesSubtitle:text(1000),principles:z.array(z.object({title:text(255),text:text(5000)})).max(30).default([]),reasonsTitle:text(255),reasonsSubtitle:text(1000),reasons:z.array(item).max(30).default([]),casesTitle:text(255),casesSubtitle:text(1000),cases:z.array(z.object({tag:text(100),title:text(500),result:text(255),text:text(3000),statValue:text(50),statUnit:text(100)})).max(30).default([]),reviewsTitle:text(255),reviewsSubtitle:text(1000),reviews:z.array(z.object({text:text(3000),name:text(255),kind:text(255)})).max(30).default([]),stats:z.array(z.object({to:z.number().int().min(0).max(1000000),suffix:text(20),label:text(255)})).max(20).default([])}).strict()
async function loadPageContent(){const [rows]=await pool.query('SELECT content, updated_at FROM about_page_content WHERE slug=? LIMIT 1',[pageSlug]);if(!rows[0])return DEFAULT_PAGE;return {...DEFAULT_PAGE,...(typeof rows[0].content==='string'?JSON.parse(rows[0].content):rows[0].content),updatedAt:rows[0].updated_at}}
async function loadAbout(){const [rows]=await pool.query('SELECT * FROM about_sections WHERE slug=? LIMIT 1',[slug]);if(!rows[0])return null;const [descriptions]=await pool.query('SELECT description FROM about_section_descriptions WHERE about_id=? ORDER BY sort_order,id',[rows[0].id]);return{slug,title:rows[0].title,imagePath:rows[0].image_path,imageUrl:abs(rows[0].image_path),imageWidth:rows[0].image_width,imageHeight:rows[0].image_height,imageAlt:rows[0].image_alt,descriptions:descriptions.map((x,i)=>({id:i+1,description:x.description})),page:await loadPageContent(),updatedAt:rows[0].updated_at}}
export const publicAbout=Router();publicAbout.get('/',async(_req,res)=>{const about=await loadAbout();if(!about)return res.status(404).json({message:'بخش دربارهٔ ما پیدا نشد'});res.set('Cache-Control','public, max-age=30');res.json(about)})
export const adminAbout=Router();adminAbout.use(requireAdmin);const imagePath=z.string().regex(UPLOAD_PATH_RE).nullable().optional();const baseSchema=z.object({title:z.string().trim().min(1).max(255),imagePath,imageAlt:z.string().trim().max(255).default(''),descriptions:z.array(z.object({description:z.string().trim().min(1).max(5000)})).min(1).max(20)})
adminAbout.get('/',async(_req,res)=>{const about=await loadAbout();if(!about)return res.status(404).json({message:'بخش دربارهٔ ما پیدا نشد'});res.json(about)})
adminAbout.put('/',async(req,res)=>{const base=baseSchema.safeParse(req.body);if(!base.success)return res.status(400).json({message:'اطلاعات اصلی دربارهٔ ما معتبر نیست'});const page=pageSchema.safeParse(req.body.page||{});if(!page.success)return res.status(400).json({message:'محتوای صفحه دربارهٔ ما معتبر نیست'});const data=base.data;const dimensions=data.imagePath?await inspectImage(diskPathOf(data.imagePath)):null;if(data.imagePath&&!dimensions)return res.status(400).json({message:'تصویر دربارهٔ ما قابل دسترسی نیست'});const conn=await pool.getConnection();try{await conn.beginTransaction();const [rows]=await conn.query('SELECT id FROM about_sections WHERE slug=? LIMIT 1 FOR UPDATE',[slug]);if(!rows[0]){await conn.rollback();return res.status(404).json({message:'بخش دربارهٔ ما پیدا نشد'})}const id=rows[0].id;await conn.query('UPDATE about_sections SET title=?,image_path=?,image_width=?,image_height=?,image_alt=? WHERE id=?',[data.title,data.imagePath??null,dimensions?.width??null,dimensions?.height??null,data.imageAlt,id]);await conn.query('DELETE FROM about_section_descriptions WHERE about_id=?',[id]);for(const [i,x] of data.descriptions.entries())await conn.query('INSERT INTO about_section_descriptions (about_id,description,sort_order) VALUES (?,?,?)',[id,x.description,i]);await conn.query('INSERT INTO about_page_content (slug,content) VALUES (?,?) ON DUPLICATE KEY UPDATE content=VALUES(content)',[pageSlug,JSON.stringify(page.data)]);await conn.commit()}catch(error){await conn.rollback();console.error(error);return res.status(500).json({message:'ذخیره دربارهٔ ما با خطا مواجه شد'})}finally{conn.release()}res.json(await loadAbout())})
