import { Router } from 'express'
import { z } from 'zod'
import { pool } from '../db.js'
import { requireAdmin } from '../middleware/auth.js'
import { UPLOAD_PATH_RE } from '../middleware/upload.js'
import { prepareContent } from '../lib/blogContent.js'
export const BLOG_CATEGORIES=['family','criminal','business','real-estate','contracts','tax']
const SLUG_RE=/^[a-z0-9]+(?:-[a-z0-9]+)*$/
const dim=z.number().int().positive().max(20000).nullable().optional()
const postSchema=z.object({slug:z.string().trim().toLowerCase().min(3).max(120).regex(SLUG_RE),title:z.string().trim().min(3).max(200),excerpt:z.string().trim().max(500).optional().default(''),category:z.enum(BLOG_CATEGORIES),author:z.string().trim().max(100).optional().default(''),coverImage:z.object({path:z.string().regex(UPLOAD_PATH_RE),width:dim,height:dim,alt:z.string().trim().max(255).optional().default('')}).nullable().optional().default(null),contentHtml:z.string().max(900000),status:z.enum(['draft','published']).default('draft'),metaTitle:z.string().trim().max(200).optional().default(''),metaDescription:z.string().trim().max(320).optional().default('')})
const SUMMARY='id, slug, title, excerpt, category, author, cover_path, cover_width, cover_height, cover_alt, reading_minutes, status, published_at, updated_at'
const json=v=>typeof v==='string'?JSON.parse(v):v
const summary=r=>({id:r.id,slug:r.slug,title:r.title,excerpt:r.excerpt,category:r.category,author:r.author,coverImage:r.cover_path?{path:r.cover_path,width:r.cover_width,height:r.cover_height,alt:r.cover_alt}:null,readingMinutes:r.reading_minutes,status:r.status,publishedAt:r.published_at,updatedAt:r.updated_at})
const post=r=>({...summary(r),contentHtml:r.content_html,toc:json(r.toc)||[],metaTitle:r.meta_title,metaDescription:r.meta_description})
const int=(v,d,min,max)=>{const n=Number.parseInt(v,10);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):d}
function body(req,res){const r=postSchema.safeParse(req.body??{});if(!r.success){res.status(400).json({message:r.error.issues?.[0]?.message||'داده‌های ارسالی معتبر نیست'});return null}const data=r.data, prepared=prepareContent(data.contentHtml);if(data.status==='published'&&prepared.isEmpty){res.status(400).json({message:'مقالهٔ خالی را نمی‌شود منتشر کرد'});return null}return {data,prepared}}
const vals=({data,prepared})=>[data.slug,data.title,data.excerpt||prepared.autoExcerpt,data.category,data.author,data.coverImage?.path??null,data.coverImage?.width??null,data.coverImage?.height??null,data.coverImage?.alt??'',prepared.html,JSON.stringify(prepared.toc),prepared.readingMinutes,data.status,data.metaTitle,data.metaDescription]
export const publicBlog=Router()
publicBlog.get('/',async(req,res)=>{const page=int(req.query.page,1,1,1000),limit=int(req.query.limit,24,1,50),where=["status='published'"],args=[],cat=typeof req.query.category==='string'?req.query.category:'';if(BLOG_CATEGORIES.includes(cat)){where.push('category=?');args.push(cat)}const q=typeof req.query.q==='string'?req.query.q.trim().slice(0,100):'';if(q){const like=`%${q.replace(/[\\%_]/g,c=>`\\${c}`)}%`;where.push('(title LIKE ? OR excerpt LIKE ?)');args.push(like,like)}const w=where.join(' AND ');const [[{total}]]=await pool.query(`SELECT COUNT(*) AS total FROM blog_posts WHERE ${w}`,args);const [rows]=await pool.query(`SELECT ${SUMMARY} FROM blog_posts WHERE ${w} ORDER BY published_at DESC,id DESC LIMIT ? OFFSET ?`,[...args,limit,(page-1)*limit]);res.set('Cache-Control','public, max-age=30');res.json({items:rows.map(summary),total:Number(total),page,limit})})
publicBlog.get('/:slug',async(req,res)=>{const slug=String(req.params.slug||'').toLowerCase();if(!SLUG_RE.test(slug))return res.status(404).json({message:'مقاله پیدا نشد'});const [rows]=await pool.query("SELECT * FROM blog_posts WHERE slug=? AND status='published' LIMIT 1",[slug]);if(!rows[0])return res.status(404).json({message:'مقاله پیدا نشد'});const p=post(rows[0]);const [related]=await pool.query(`SELECT ${SUMMARY} FROM blog_posts WHERE status='published' AND id<>? ORDER BY (category=?) DESC,published_at DESC LIMIT 3`,[p.id,p.category]);res.set('Cache-Control','public, max-age=30');res.json({post:p,related:related.map(summary)})})
export const adminBlog=Router();adminBlog.use(requireAdmin)
adminBlog.get('/',async(_req,res)=>{const [rows]=await pool.query(`SELECT ${SUMMARY} FROM blog_posts ORDER BY updated_at DESC,id DESC`);res.json(rows.map(summary))})
adminBlog.get('/:id',async(req,res)=>{const [rows]=await pool.query('SELECT * FROM blog_posts WHERE id=? LIMIT 1',[int(req.params.id,0,0,2**31)]);if(!rows[0])return res.status(404).json({message:'مقاله پیدا نشد'});res.json(post(rows[0]))})
adminBlog.post('/',async(req,res)=>{const x=body(req,res);if(!x)return;try{const [r]=await pool.query(`INSERT INTO blog_posts (slug,title,excerpt,category,author,cover_path,cover_width,cover_height,cover_alt,content_html,toc,reading_minutes,status,meta_title,meta_description,published_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,${x.data.status==='published'?'NOW()':'NULL'})`,vals(x));const [rows]=await pool.query('SELECT * FROM blog_posts WHERE id=?',[r.insertId]);res.status(201).json(post(rows[0]))}catch(e){if(e.code==='ER_DUP_ENTRY')return res.status(409).json({message:'این نامک قبلاً استفاده شده است'});throw e}})
adminBlog.put('/:id',async(req,res)=>{const id=int(req.params.id,0,0,2**31),x=body(req,res);if(!x)return;try{const [r]=await pool.query(`UPDATE blog_posts SET slug=?,title=?,excerpt=?,category=?,author=?,cover_path=?,cover_width=?,cover_height=?,cover_alt=?,content_html=?,toc=?,reading_minutes=?,status=?,meta_title=?,meta_description=?,published_at=CASE WHEN status='published' AND published_at IS NULL THEN NOW() ELSE published_at END WHERE id=?`,[...vals(x),id]);if(!r.affectedRows)return res.status(404).json({message:'مقاله پیدا نشد'});const [rows]=await pool.query('SELECT * FROM blog_posts WHERE id=?',[id]);res.json(post(rows[0]))}catch(e){if(e.code==='ER_DUP_ENTRY')return res.status(409).json({message:'این نامک قبلاً استفاده شده است'});throw e}})
adminBlog.delete('/:id',async(req,res)=>{const [r]=await pool.query('DELETE FROM blog_posts WHERE id=?',[int(req.params.id,0,0,2**31)]);if(!r.affectedRows)return res.status(404).json({message:'مقاله پیدا نشد'});res.json({ok:true})})
